parameters:
# nothing to declare

services:
  LeoVie\PhpFilesystem\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/PhpFilesystemBundle.php'

  LeoVie\PhpFilesystem\Service\Filesystem:
    alias: LeoVie\PhpFilesystem\Service\FilesystemService
    public: true